services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=skillflowai'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
